# Generated by Django 4.2.6 on 2024-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-user-profile.png', upload_to='profile_images'),
        ),
    ]
